abc(129b): Aboid double-loop

diff --git a/bin/atcoder b/bin/atcoder
--- a/bin/atcoder
+++ b/bin/atcoder
@@ -4,7 +4,7 @@ ATCODER_DIR=$(
   cd $(dirname $0)/../atcoder
   pwd
 )
-IS_ATCODER="a(b|g|r)c[0-9]{3}"
+# IS_ATCODER="a(b|g|r)c[0-9]{3}"
 
 function init() {
   if [ $# -eq 0 ]; then
@@ -15,10 +15,10 @@ function init() {
   CONTEST=$1
   PROBLEM=$2
 
-  if [[ ! $CONTEST =~ $IS_ATCODER ]]; then
-    echo "Error: Invalid Format"
-    exit 1
-  fi
+  # if [[ ! $CONTEST =~ $IS_ATCODER ]]; then
+  #   echo "Error: Invalid Format"
+  #   exit 1
+  # fi
 
   if [ ! -d $ATCODER_DIR/$CONTEST ]; then
     mkdir -p $ATCODER_DIR/$CONTEST
